# Generated by Django 3.0.3 on 2020-03-22 18:43

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forward_category(apps, schema_editor):
    Category = apps.get_model("blog", "Category")
    db_alias = schema_editor.connection.alias
    Category.objects.using(db_alias).get_or_create(name="Uncategorized")


def reverse_category(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=models.SET(blog.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
            ],
        ),
        migrations.RunPython(forward_category, reverse_code=reverse_category)
    ]
